version: "3"
services:
  web:
    env_file:
      - env_file
    build:
      context: ./web
    ports:
      - "80:80"
      - "443:443"
  api:
    env_file:
      - env_file
    build:
      context: ./api
    ports:
      - "80:80"
      - "443:443"
