[package]
name = "sudothei-website"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.6.1"
actix-web = "4.1.0"
bcrypt = "0.13.0"
bson = "2.3.0"
jwt = "0.16.0"
mongodb = "2.2.2"
serde = "1.0.139"
tokio-stream = "0.1.9"
